name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (modify as per your needs)
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          pip install selenium
          pip install beautifulsoup4
          pip install schedule  # All required packages

      - name: Run the Python script
        run: |
          python3 NFT_notification.py  # Replace with your script's name
