name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (modify as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    resources:
      limits:
        memory: 4G
        cpu: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install beautifulsoup4
          pip install schedule

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              google-chrome-stable \
              libappindicator3-1 \
              fonts-liberation \
              xdg-utils \
              libxss1 \
              libgconf-2-4 \
              libgbm-dev \
              libgtk-3-0

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -yqq unzip
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/

      - name: Run the Python script
        env:
          PATH: /usr/local/bin/chromedriver:$PATH
        run: |
          python3 NFT_notification.py
